name: Run AstroLotto

on:
  workflow_dispatch:  # 转 专抓 转
  schedule:
    - cron: '0 5 * * *'  #   志05:00 UTC

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Debug folder structure
        run: |
          echo " Files in root:"
          ls -la
          echo " Files in astro_server:"
          ls -la astro_server

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flatlib==0.2.0
          pip install -r astro_server/requirements.txt

      - name: Run server.py
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python astro_server/server.py
